services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      # Persist the backend's 'data' folder to a fixed location on the host
      - ./backend/data:/app/data
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "4200:80"